spring:
  application:
    name: person-service
  datasource:
    name: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/person_service
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/person_service
    user: postgres
    password: admin
    locations:
      classpath:db/migration
    baselineOnMigrate: true
  cloud:
    stream:
      function:
        definition: person
      bindings:
        person-in-0:
          destination: person
          group: personGroup
      kafka:
        streams:
          consumer:
            max-poll-records: 10
            auto-offset-reset: earliest
            enable-auto-commit: false
            configuration:
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          binder:
            brokers: 127.0.0.1:9092
            autoCreateTopics: true